environment:

  matrix:
  - TARGET: x86_64-pc-windows-msvc
  - TARGET: i686-pc-windows-msvc
  - rust_version: 1.10.0
  - rust_version: nightly

matrix:
  allow_failures:
  - rust_version: nightly

install:
- ps: >
   (new-object Net.WebClient).DownloadFile(
        "https://static.rust-lang.org/dist/rust-${env:rust_version}-${env:TARGET}.exe",
        "${pwd}\rust-${env:rust_version}-${env:TARGET}.exe"
    )
- rust-%rust_version%-%TARGET%.exe /VERYSILENT /NORESTART /DIR="C:\Rust"
- set PATH=%PATH%;C:\Rust\bin
- rustc -V
- cargo -V

before_build:
- nuget restore Generator\Generator.sln

after_build:
- .\Generator\bin\Release\Generator.exe .\src\rt\gen.rs
- cargo build --verbose





